import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: {
        sm: "100%",
        md: "720px",
        lg: "960px",
        xl: "1280px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["'Pretendard Variable'", "'Noto Sans KR'", "sans-serif"],
      },
      fontSize: {
        h1: ["32px", { lineHeight: "40px", fontWeight: "800" }],
        h2: ["24px", { lineHeight: "32px", fontWeight: "700" }],
        h3: ["20px", { lineHeight: "28px", fontWeight: "700" }],
        title: ["18px", { lineHeight: "26px", fontWeight: "700" }],
        body: ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-strong": ["16px", { lineHeight: "26px", fontWeight: "600" }],
        caption: ["14px", { lineHeight: "22px", fontWeight: "500" }],
        label: ["13px", { lineHeight: "18px", fontWeight: "600" }],
        button: ["15px", { lineHeight: "22px", fontWeight: "700" }],
      },
      spacing: {
        "sp-1": "4px",
        "sp-2": "8px",
        "sp-3": "12px",
        "sp-4": "16px",
        "sp-5": "20px",
        "sp-6": "24px",
        "sp-7": "32px",
        "sp-8": "40px",
        "sp-9": "48px",
        "sp-10": "64px",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        "bg-surface": "hsl(var(--bg-surface))",
        "bg-subtle": "hsl(var(--bg-subtle))",
        "bg-elevated": "hsl(var(--bg-elevated))",
        "bg-inverse": "hsl(var(--bg-inverse))",
        "text-secondary": "hsl(var(--text-secondary))",
        "text-muted": "hsl(var(--text-muted-val))",
        "text-inverse": "hsl(var(--text-inverse))",
        "line-strong": "hsl(var(--line-strong))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
          active: "hsl(var(--primary-active))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          pink: "hsl(var(--accent-pink))",
          mint: "hsl(var(--accent-mint))",
          sky: "hsl(var(--accent-sky))",
          lavender: "hsl(var(--accent-lavender))",
          coral: "hsl(var(--accent-coral))",
        },
        state: {
          success: "hsl(var(--state-success))",
          "success-soft": "hsl(var(--state-success-soft))",
          warning: "hsl(var(--state-warning))",
          "warning-soft": "hsl(var(--state-warning-soft))",
          error: "hsl(var(--destructive))",
          "error-soft": "hsl(var(--state-error-soft))",
          info: "hsl(var(--state-info))",
          "info-soft": "hsl(var(--state-info-soft))",
        },
        element: {
          wood: "hsl(var(--element-wood))",
          fire: "hsl(var(--element-fire))",
          earth: "hsl(var(--element-earth))",
          metal: "hsl(var(--element-metal))",
          water: "hsl(var(--element-water))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        sm: "0 4px 16px rgba(36,48,63,0.08)",
        md: "0 8px 24px rgba(36,48,63,0.10)",
        lg: "0 16px 40px rgba(36,48,63,0.12)",
      },
      zIndex: {
        sticky: "10",
        gnb: "20",
        "bottom-tab": "30",
        "sticky-cta": "40",
        drawer: "50",
        modal: "60",
        toast: "70",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        shimmer: "shimmer 1.2s infinite linear",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
